# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Publish weather to Spreadsheet
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      env:
        TYPE: ${{ secrets.GOOGLE_TYPE }}
        CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}      
    - run: npm ci
    - run: npm run build --if-present
    - run: node index.js
